get http://localhost:3000/users/

###
post http://localhost:3000/users
Content-Type: application/json

{
    "name": "Mary Rogers",
    "email": "mary@example.com"
}

###
PUT http://localhost:3000/users/2
Content-Type: application/json

{
    "name": "Jack Smith",
    "email": "jack@example.com"
}

###
DELETE http://localhost:3000/users/2